#!/bin/bash

ip_found=false

ip_regex="[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}"
ip_list=$(ifconfig | grep -oE "inet $ip_regex" | grep -oE "$ip_regex")

while read item; do
    if [[ "$item" != "127.0.0.1" ]]; then
        ip_found=true
        break
    fi
done <<< "$ip_list"

if ! $ip_found; then
    echo "IP address for binding not found!" >&2
    exit 1
fi

rails s -b "$item"
